# Author: Vu Viet Tai
version: "3.7"
volumes:
  smartform-data:
services:
  smartform-apidb:
    image: postgres:14.9-alpine3.18
    container_name: smartform-apidb
    volumes:
      - smartform-data:/var/lib/postgresql/data
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DATASOURCE_DB:-smartform_data}
      POSTGRES_USER: ${DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${DATASOURCE_PASSWORD}
      PGDATA: /var/lib/postgresql/data
    ports:
      - "${DATASOURCE_PORT:-5432}:5432"

  smartform-api:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    image: smartform-api
    container_name: smartform-api
    restart: always
    volumes:
      - ../:/smartform_bpm
    ports:
      - "${SMARTFORM_API_PORT:-8080}:8080"
    environment:
      - DATASOURCE_HOST=smartform-apidb
      - DATASOURCE_PORT=5432
      - DATASOURCE_DB=${DATASOURCE_DB:-smartform_data}
      - DATASOURCE_USERNAME=${DATASOURCE_USERNAME}
      - DATASOURCE_PASSWORD=${DATASOURCE_PASSWORD}
      - QUARKUS_KEYCLOAK_DEVSERVICES_ENABLED:false
      - QUARKUS_OIDC_AUTH_SERVER_URL=${KEYCLOAK_URL}/realms/${KEYCLOAK_REALM}
      - QUARKUS_OIDC_CLIENT_ID=${KEYCLOAK_CLIENT_ID:-smartform-backend}
      - QUARKUS_OIDC_CLIENT_SECRET=${KEYCLOAK_CLIENT_SECRET}
      - KEYCLOAK_URL=${KEYCLOAK_URL}
      - KEYCLOAK_URL_REALM=${KEYCLOAK_REALM:-smartform}
      - KEYCLOAK_ENABLE_CLIENT_AUTH=${KEYCLOAK_ENABLE_CLIENT_AUTH:-false}
      - BPM_CLIENT_CONN_TIMEOUT=${BPM_CLIENT_CONN_TIMEOUT:-5000}
      - CAMUNDA_JDBC_URL=${CAMUNDA_JDBC_URL:-jdbc:postgresql://forms-flow-bpm-db:5432/formsflow-bpm}
      - CAMUNDA_JDBC_USER=${CAMUNDA_JDBC_USER}
      - CAMUNDA_JDBC_PASSWORD=${CAMUNDA_JDBC_PASSWORD}
      - CAMUNDA_JDBC_DRIVER=${CAMUNDA_JDBC_DRIVER:-org.postgresql.Driver}
      - CAMUNDA_APP_ROOT_LOG_FLAG=${CAMUNDA_APP_ROOT_LOG_FLAG:-error}
      - FORMSFLOW_API_URL=${FORMSFLOW_API_URL}
      - FORMIO_URL=${FORMIO_DEFAULT_PROJECT_URL}
      - FORMIO_ROOT_EMAIL=${FORMIO_ROOT_EMAIL}
      - FORMIO_ROOT_PASSWORD=${FORMIO_ROOT_PASSWORD}
      - APP_SECURITY_ORIGIN=${APP_SECURITY_ORIGIN:-*}
      - WEBSOCKET_SECURITY_ORIGIN=${WEBSOCKET_SECURITY_ORIGIN}
      - WEBSOCKET_MESSAGE_TYPE=${WEBSOCKET_MESSAGE_TYPE:-TASK_EVENT}
      - WEBSOCKET_ENCRYPT_KEY=${WEBSOCKET_ENCRYPT_KEY:-giert989jkwrgb@DR55}
      - DATA_BUFFER_SIZE=${DATA_BUFFER_SIZE:-2}
      - IDENTITY_PROVIDER_MAX_RESULT_SIZE=${IDENTITY_PROVIDER_MAX_RESULT_SIZE:-250}
      - DATA_ANALYSIS_URL=${DATA_ANALYSIS_URL}
